### ISSUE TITLE
what about wheels ?

### ISSUE THREAD

**Issue by stonebig** [denfromufa/clrmagic#1]

**Comment by den-run-ai** [comment]
I tried `python setup.py bdist_wheel --universal` but it is not making
universal wheels - rather version dependent.

**Comment by stonebig** [comment]
I have issues to create the python3.4-32bit one, the others I can do.

**Comment by den-run-ai** [comment]
it builds fine for me, see attached.

**Comment by stonebig** [comment]
attached ??

**Comment by den-run-ai** [comment]
How about now? I sent it to your gmail.

clrmagic-0.0.1a2-cp34-cp34m-win32.whl
https://drive.google.com/file/d/0Bxa9pLe-A3FHSm1vNW5CNHFyX2M/view?usp=sharing

**Comment by stonebig** [comment]
perfect, thanks !

**Comment by den-run-ai** [comment]
I just "hacked" the wheel and uploaded universal wheel to pypi which should
install on any platform any python, Mono/.NET (not CoreCLR).

https://pypi.python.org/packages/2a/8a/0fa3e5ec55cc2b80dc0fe12645810b3f819065801a3228a46ba845c1d2ef/clrmagic-0.0.1a2-py2.py3-none-any.whl#md5=8c8faec97c0fe484b31cd3fae51c9e8d

**Comment by stonebig** [comment]
by the way, any perspective of update of pythonnet ?

**Comment by den-run-ai** [comment]
I would like to resolve few things on overloading (constructor, subtypes
and ref/out), but we could release an alpha/beta versions in between.

**Comment by stonebig** [comment]
Do I guess well that coming alpha would already have less bugs than last official release ?

**Comment by den-run-ai** [comment]
Yes for fixed issues (relative imports, upgraded unmanaged exports, etc.),
not 100% sure for new features (recursive types). Like always, there may be
regressions not covered by the current testing CI. Also we updated the docs
and added wiki content.

Can you see the draft release notes?

https://github.com/pythonnet/pythonnet/releases/tag/untagged-ba1407b47261aca9878a

**Comment by stonebig** [comment]
no. I can't see  where it is, just saw a lot of nasty bug being fixed
